steps:
- name: 'asia.gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/sailor-321711/react-image:v1', '.' ]

- name: 'asia.gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/sailor-321711/react-image:v1']